#!/bin/bash
# Launch script for Password Gorilla
DIR="$(cd "$(dirname "$0")" && pwd)"
RESOURCES="$DIR/../Resources"
export TCL_LIBRARY="$RESOURCES/lib/tcl9.0"
export TK_LIBRARY="$RESOURCES/lib/tk9.0"
export TCLLIBPATH="$RESOURCES/lib"
export TCL9_TM_PATH="$RESOURCES/lib/tcl9"
exec "$DIR/Password Gorilla" "$RESOURCES/sources/gorilla.tcl" "$@"
