#!/bin/bash
# Launch script for Password Gorilla
DIR="$(cd "$(dirname "$0")" && pwd)"
CONTENTS="$DIR/.."
RESOURCES="$CONTENTS/Resources"
export TCL_LIBRARY="$CONTENTS/lib/tcl9.0"
export TK_LIBRARY="$CONTENTS/lib/tk9.0"
export TCLLIBPATH="$CONTENTS/lib"
export TCL9_TM_PATH="$CONTENTS/lib/tcl9"
exec "$DIR/Password Gorilla" "$RESOURCES/sources/gorilla.tcl" "$@"
